"""
Transaction contract — Centinela (Deliverable 15).

The four explicit decisions required by requirement 2.8:

1. TIMESTAMP: `occurred_at` travels in UTC (ISO 8601 with timezone). The server
   additionally records `received_at` (generated by the API, not the client).
   The Week 2 velocity rule will use `received_at`: the client cannot
   manipulate it. Future timestamps are rejected (> now + 120 s clock skew).

2. AMOUNT: integer in minor units (cents) + ISO 4217 currency code.
   Never floating point: 0.1 + 0.2 != 0.3 in IEEE-754 — unacceptable for money.

3. LOCATION: decimal latitude/longitude (WGS-84). Enables the Haversine
   distance calculation required by the geo-impossible rule. Validated ranges:
   lat [-90, 90], lon [-180, 180].

4. IDENTIFIER: `transaction_id` is a UUID generated by the CLIENT (the
   transaction issuer), which enables idempotency: if the same id arrives
   twice, the API returns the same acknowledgment without duplicating
   persistence (a blob with the same name is overwritten with identical
   content => net-zero effect).

Unknown fields: policy = REJECT (extra="forbid"). An unknown field may be an
issuer bug or an injection attempt; a financial system prefers to fail
explicitly.
"""
from datetime import datetime, timezone, timedelta
from pydantic import BaseModel, Field, field_validator
import uuid

CURRENCIES = {"COP", "USD", "EUR"}
MAX_AMOUNT_MINOR = 50_000_000_000  # "reasonable" cap: 500 million COP in cents


class Location(BaseModel):
    model_config = {"extra": "forbid"}
    lat: float = Field(ge=-90, le=90)
    lon: float = Field(ge=-180, le=180)


class Transaction(BaseModel):
    model_config = {"extra": "forbid"}

    transaction_id: uuid.UUID                    # decision 4
    account_id: str = Field(min_length=4, max_length=64)    # which account?
    amount_minor: int = Field(gt=0, le=MAX_AMOUNT_MINOR)    # decision 2: what amount?
    currency: str                                # ISO 4217
    occurred_at: datetime                        # decision 1: at what exact instant?
    location: Location                           # decision 3: from where?
    merchant_id: str = Field(min_length=1, max_length=64)   # toward which merchant?
    merchant_category: str = Field(min_length=1, max_length=32)

    @field_validator("currency")
    @classmethod
    def currency_supported(cls, v: str) -> str:
        if v not in CURRENCIES:
            raise ValueError("unsupported currency")
        return v

    @field_validator("occurred_at")
    @classmethod
    def no_future_timestamps(cls, v: datetime) -> datetime:
        if v.tzinfo is None:
            raise ValueError("timestamp must include a timezone")
        if v > datetime.now(timezone.utc) + timedelta(seconds=120):
            raise ValueError("future timestamp")
        return v.astimezone(timezone.utc)
