"""
Centinela — Ingestion API (Week 1).

Required behavior, in order (requirement 2.9):
  1. Receive  2. Validate contract  3. Persist raw  4. Acknowledge.
It does NOT query history, compute scores, apply rules or open cases.

Status code table (Deliverable 18):
  202  Valid transaction accepted and persisted (asynchronous acknowledgment).
  400  Malformed JSON / missing fields / wrong types / extra fields /
       amount out of range / future timestamp / invalid coordinates.
  409  Duplicate document (target name already exists).
  413  Document exceeds the maximum size.
  415  File type not allowed (validated by real content, not extension).
  422  (Normalized to 400: we expose only the field and a generic reason,
       never internal validation details.)
  500  Internal error; the body never exposes traces or resource names.
"""
import json
import os
import uuid
from datetime import datetime, timezone

from fastapi import FastAPI, HTTPException, Request, UploadFile, File
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse

from .contract import Transaction
from . import storage, events

app = FastAPI(title="Centinela — Ingestion API", version="0.1.0")

MAX_UPLOAD_BYTES = int(os.environ.get("MAX_UPLOAD_MB", "5")) * 1024 * 1024

# Validation by real content (magic bytes), never by extension (requirement 2.10)
SIGNATURES = {
    b"%PDF": ("application/pdf", "pdf"),
    b"\xff\xd8\xff": ("image/jpeg", "jpg"),
    b"\x89PNG\r\n\x1a\n": ("image/png", "png"),
}


@app.exception_handler(RequestValidationError)
async def validation_handler(_req: Request, exc: RequestValidationError):
    # Useful message for the issuer without exposing system internals.
    details = [
        {"field": ".".join(str(p) for p in e["loc"] if p != "body"),
         "reason": e["msg"]}
        for e in exc.errors()
    ]
    return JSONResponse(status_code=400,
                        content={"error": "invalid_payload", "details": details})


@app.get("/health")
def health():
    return {"status": "ok"}


@app.post("/transactions", status_code=202)
def ingest(tx: Transaction):
    # 3. Persist the raw transaction (idempotent by transaction_id)
    record = tx.model_dump(mode="json")
    record["received_at"] = datetime.now(timezone.utc).isoformat()
    storage.persist_transaction(str(tx.transaction_id), json.dumps(record))

    # Week 2 insertion point (no-op today): publish event after persisting.
    events.publish_transaction_received(str(tx.transaction_id))

    # 4. Acknowledge. The acknowledgment is issued AFTER persisting:
    #    the only point in the sequence where it is safe (requirement 2.12).
    return {"status": "accepted", "transaction_id": str(tx.transaction_id)}


@app.post("/cases/{case_id}/documents", status_code=201)
async def upload_document(case_id: str, file: UploadFile = File(...)):
    data = await file.read()

    if len(data) > MAX_UPLOAD_BYTES:
        raise HTTPException(413, detail={"error": "document_exceeds_max_size"})

    detected = next(((ct, ext) for magic, (ct, ext) in SIGNATURES.items()
                     if data.startswith(magic)), None)
    if detected is None:
        raise HTTPException(415, detail={"error": "file_type_not_allowed"})
    content_type, ext = detected

    # The target name is generated by the SYSTEM (requirement 2.10):
    # case id + UUID. The user-provided filename is a known attack vector
    # and is never used.
    target_name = f"{case_id}/{uuid.uuid4()}.{ext}"
    try:
        storage.store_document(target_name, data, content_type)
    except Exception:
        raise HTTPException(409, detail={"error": "storage_conflict"})

    return {"status": "stored", "blob": target_name}
